accounts/urls.py
from django.urls import path
from .views import (StudentSignUpView, LecturerSignUpView, UpdateStudent,
                    user_login, student_image_login, image_registration,
                    StudentDetail, LecturerDetail, UpdateLecturer, UpdateUser)
from django.contrib.auth import views

app_name = 'accounts'

urlpatterns = [
    path('lecturer/register/', LecturerSignUpView.as_view(),
         name='lecturer_register'),
    path('add-student/', StudentSignUpView.as_view(), name='add_student'),
    path('user/login/', user_login, name='user_login_redirect'),
    path('student/image/login/<int:pk>/',
         student_image_login, name='student_image_login'),
    path('update-student/<int:pk>/',
         UpdateStudent.as_view(), name='update_student'),
    path('student/details/<int:pk>/',
         StudentDetail.as_view(), name='student_detail'),
    path('lecturer/details/<int:pk>/',
         LecturerDetail.as_view(), name='lecturer_detail'),
    path('update-lecturer/<int:pk>/',
         UpdateLecturer.as_view(), name='update_lecturer'),
    path('update-user/<int:pk>/',
         UpdateUser.as_view(), name='update_user'),
    path('image-registration/<int:pk>',
         image_registration, name='image_register'),
    path('reset', views.PasswordResetView.as_view(
        template_name='password_reset_form.html', email_template_name='password_reset_email.html',
        subject_template_name='password_reset_subject.txt'),
        name='password_reset'
    ),

    path('reset/done', views.PasswordResetDoneView.as_view(
        template_name='password_reset_done.html'
    ), name='password_reset_done'),

    path('reset/<uidb64>/<token>/', views.PasswordResetConfirmView.as_view(
        template_name='password_reset_confirm.html'),
        name='password_reset_confirm'),

    path('account/reset/complete/',
         views.PasswordResetCompleteView.as_view(
             template_name='password_reset_complete.html'),
         name='password_reset_complete'),

    path('settings/password/', views.PasswordChangeView.as_view(template_name='password_change.html'),
         name='password_change'),

    path('settings/password/done/', views.PasswordChangeDoneView.as_view(
        template_name='password_change_done.html'),
        name='password_change_done'
    ),

    path('login/', views.LoginView.as_view(template_name='login.html'), name='login'),

]

course/urls.py
from django.urls import path
from .views import (dashboard, CreateCourse, CourseList, StudentProfile, StudentsPerCourseList, student_course_registration, all_students_per_lecturer,
                    take_attendance, attendance_per_course,attendance_per_course_breakdown, AttendanceUpdate, 
                    calculate_percentage_of_attendance)

app_name = 'course'

urlpatterns = [
    path('dashboard/', dashboard, name='user_dashboard'),
    path('create-course/', CreateCourse.as_view(), name='create_course'),
    path('courses-list', CourseList.as_view(), name='course_list'),
    path('lecturer/student/<int:pk>', StudentProfile.as_view(), name='lecturer_student'),
    path('course/students/<int:pk>', StudentsPerCourseList.as_view(), name='courses_per_students'),

    path('student/<int:pk>/registration/',
         student_course_registration, name='student_registration'),
    path('all/student/',
         all_students_per_lecturer, name='all_student_per_lecturer'),

    path('attendance-update/<int:pk>/',
         AttendanceUpdate.as_view(), name='attendance_update'),
    path('take-attendance/<int:course_id>',
         take_attendance, name='take_attendance'),
    path('view-attendance/<int:course_id>',
         attendance_per_course, name='view_attendance'),
    path('view-attendance/marks/<int:course_id>',
         calculate_percentage_of_attendance, name='view_attendance_marks'),
    path('view-attendance-breakdown/<int:course_id>/<slug:attendance_date>', attendance_per_course_breakdown,
         name='view_attendance_breakdown')


]

facettendace/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('', include('course.urls'))
]


if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls))] + urlpatterns
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)

accounts/models.py
from django.contrib.auth.models import AbstractUser
from django.contrib.auth.models import User
from django.db import models
from django.utils.translation import ugettext_lazy as _
from phonenumber_field.modelfields import PhoneNumberField

from .validators import UnicodeUsernameValidator


class User(AbstractUser):
    MALE = 'MALE'
    FEMALE = 'FEMALE'
    OTHERS = 'OTHERS'
    GENDER_CHOICES = [
        (MALE, 'Male'),
        (FEMALE, 'Female'),
        (OTHERS, 'Others'),
    ]
    username = models.CharField(max_length=40, unique=True)
    email = models.EmailField(_('email address'), null=True,)

    USERNAME_FIELD = 'username'

    gender = models.CharField(choices=GENDER_CHOICES, max_length=6)
    dept = models.CharField(_("Your Department"), blank=True, max_length=255)
    phone_number = PhoneNumberField(blank=True, default='')
    address = models.CharField(max_length=500, default='')
    is_student = models.BooleanField(default=False)
    is_teacher = models.BooleanField(default=False)

    # REQUIRED_FIELDS = ['email', 'username']

    def __init__(self, *args, **kwargs):
        validate_username = UnicodeUsernameValidator()
        super(User, self).__init__(*args, **kwargs)
        self._meta.get_field('username').validators = [validate_username]


class Lecturer(models.Model):
    user = models.OneToOneField(
        User, on_delete=models.CASCADE, primary_key=True)

    qualification = models.CharField(max_length=200)
    image = models.ImageField(upload_to='lecturers', null=True, blank=True)

    class Meta:
        verbose_name = "Lecturer"
        verbose_name_plural = "Lecturers"

    def __str__(self):
        return self.user.username

    @property
    def full_name(self):
        return f"{self.user.first_name} {self.user.last_name}"

    @property
    def courses_registered(self):
        return self.course_set.all()


class Student(models.Model):
    LEVEL_ONE = '100'
    LEVEL_TWO = '200'
    LEVEL_THREE = '300'
    LEVEL_FOUR = '400'
    LEVEL_FIVE = '500'
    LEVEL_SIX = '600'

    LEVEL_CHOICE = [
        (LEVEL_ONE, '100L'),
        (LEVEL_TWO, '200L'),
        (LEVEL_THREE, '300L'),
        (LEVEL_FOUR, '400L'),
        (LEVEL_FIVE, '500L'),
        (LEVEL_SIX, '600L'),

    ]
    user = models.OneToOneField(
        User, on_delete=models.CASCADE, primary_key=True)
    image = models.ImageField(upload_to='students', null=True, blank=True)

    level = models.CharField(_('Your Level'), blank=True,
                             choices=LEVEL_CHOICE, max_length=4)

    def __str__(self):
        return self.user.username

    @property
    def full_name(self):
        return f"{self.user.first_name} {self.user.last_name}"

    @property
    def courses_registered(self):
        return self.studentcourseregistration_set.filter(active=True)

# @receiver(post_save, sender=User)
# def create_or_update_lecturer_profile(sender, instance, created, **kwargs):
#     if created:
#         Lecturer.objects.create(user=instance)
#     instance.lecturer.save()

course/views.py
from datetime import datetime

from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, get_object_or_404, redirect
from django.urls import reverse, reverse_lazy
from django.utils.datastructures import MultiValueDictKeyError
from django.utils.decorators import method_decorator
from django.views.generic import DetailView
from django.views.generic.edit import CreateView, UpdateView
from django.views.generic.list import ListView

from accounts.decorator import student_required, teacher_required
from accounts.models import Lecturer, Student
from accounts.utils import face_rec_login
from .forms import AttendanceForm
from .models import Course, Attendance, StudentCourseRegistration


@login_required
def dashboard(request):
    # lecturer = Lecturer.objects.get(user=request.user)
    context = {}
    if request.user.lecturer:
        courses = Course.objects.filter(lecturer__user=request.user).count()
        attendances = Attendance.objects.filter(course__lecturer__user=request.user).count()
        students = StudentCourseRegistration.objects.filter(course__lecturer__user=request.user).count()
        context = {
            'courses': courses,
            'attendances': attendances,
            'students': students
        }
    return render(request, 'dashboard.html', context)


@login_required
def lecturer_dashboard(request):
    # lecturer = Lecturer.objects.get(user=request.user)
    context = {}
    if request.user.lecturer:
        courses = Course.objects.filter(lecturer__user=request.user).count()
        attendances = Attendance.objects.filter(course__lecturer=request.user).count()
        students = StudentCourseRegistration.objects.filter(course__lecturer=request.user).count()
        context = {
            'courses': courses,
            'attendances': attendances,
            'students': students
        }
    return render(request, 'dashboard.html', context)


@method_decorator([login_required, teacher_required], name='dispatch')
class CreateCourse(CreateView):
    model = Course
    fields = ['course_code', 'course_name']
    template_name = 'create_course.html'

    def form_valid(self, form):
        """If the form is valid, save the associated model."""
        self.object = form.save(commit=False)
        lecturer = get_object_or_404(Lecturer, user=self.request.user)
        self.object.lecturer = lecturer
        print(self.object.lecturer)
        self.object.save()
        return super().form_valid(form)

    def get_success_url(self):
        """Return the URL to redirect to after processing a valid form."""
        if not self.success_url:
            return reverse_lazy('course:course_list')


@method_decorator([login_required, teacher_required], name='dispatch')
class CourseList(ListView):
    model = Course
    template_name = 'course_list.html'
    context_object_name = 'courses'

    def get_queryset(self):
        lecturer = get_object_or_404(Lecturer, user=self.request.user)
        return Course.objects.filter(lecturer=lecturer)

    # def get_context_data(self, **kwargs):
    #     context = super().get_context_data(**kwargs)
    #     courses = list(self.get_queryset().values_list('id', flat=True))
    #     context["sudents_registered"] =  StudentCourseRegistration.objects.filter(course_id__in=courses).filter(active=True)
    #     return context


@method_decorator([login_required, teacher_required], name='dispatch')
class StudentProfile(DetailView):
    model = Student
    template_name = 'student-profile.html'
    context_object_name = 'student'

    def get_queryset(self, *args, **kwargs):
        pk = self.kwargs.get('pk')
        return Student.objects.filter(pk=pk)


@method_decorator([login_required, teacher_required], name='dispatch')
class StudentsPerCourseList(ListView):
    model = StudentCourseRegistration
    template_name = 'all-students.html'
    context_object_name = 'students'

    def get_queryset(self, *args, **kwargs):
        course_pk = self.kwargs.get('pk')
        return StudentCourseRegistration.objects.filter(course_id=course_pk).filter(active=True)


@login_required
@teacher_required
def all_students_per_lecturer(request):
    lecturer = get_object_or_404(Lecturer, user=request.user)
    courses = list(Course.objects.filter(
        lecturer=lecturer).values_list('id', flat=True))
    students = StudentCourseRegistration.objects.filter(
        course_id__in=courses).filter(active=True)
    context = {
        'students': students,
    }
    return render(request, 'all-students.html', context)


def student_course_registration_processing(course_array, student, status):
    for course in course_array:
        StudentCourseRegistration.objects.update_or_create(
            student=student,
            course=course,
            defaults={'active': status}
        )


@login_required
@student_required
def student_course_registration(request, pk):
    student = Student.objects.get(pk=pk)
    courses = Course.objects.all()
    courses_registered = list(student.studentcourseregistration_set.filter(
        active=True).values_list('course', flat=True))

    if request.method == 'POST':
        try:
            print(request.POST.getlist('selected_courses'))
            selected_courses = [
                int(i) for i in request.POST.getlist('selected_courses')]
        except MultiValueDictKeyError:
            return redirect(reverse('accounts:student_detail', args=[pk]))
        old_courses = list(set(courses_registered) - set(selected_courses))
        print(selected_courses)
        adding_selected_courses = student_course_registration_processing(
            selected_courses, student, True)
        if old_courses:
            removing_old_courses = student_course_registration_processing(
                old_courses, student, False)
        messages.success(request, 'Courses added successfully')
        return redirect(reverse('accounts:student_detail', args=[pk]))
    context = {
        'student': student,
        'courses': courses,
        'courses_registered': courses_registered
    }

    return render(request, 'student_register_courses.html', context)


# def student_course_registration_processing(request):
#     student = Student.objects.get(id=id)
#     courses = Course.objects.all()
#     courses_registered = list(student.studentcourseregistration_set.all().values_list('course', flat=True))
#     context = {
#         'student':student,
#         'courses':courses,
#         'courses_registered': courses_registered
#     }

#     return render(request, 'student_register_courses.html', context)


@login_required
@teacher_required
def take_attendance(request, course_id):
    course = get_object_or_404(Course, id=course_id)
    student_registered_for_course = course.studentcourseregistration_set.filter(
        active=True).values_list('student')
    students = Student.objects.filter(
        pk__in=student_registered_for_course).filter(image__isnull=False)
    first_names = list(students.values_list('user__first_name', flat=True))
    matric_nos = list(students.values_list('user__username', flat=True))
    images_array = []
    for student in students:
        images_array.append(student.image.path)
    recgonized_faces_matric_no = face_rec_login(
        images_array, first_names, matric_nos)
    attendance, _ = Attendance.objects.get_or_create(
        course=course,
        date_recorded=datetime.today(),
        # defaults={'status': True}
    )
    for matric_no in matric_nos:
        student = get_object_or_404(Student, user__username=matric_no)
        if matric_no in recgonized_faces_matric_no:
            attendance.student.add(student)
            attendance.save()
        # else:
        #     Attendance.objects.get_or_create(
        #         course=course,
        #         student=student,
        #         defaults={'status': False}
        #     )

    return redirect(reverse('course:view_attendance', args=(course.id,)))


def attendance_per_course(request, course_id):
    # attendance_list = Attendance.objects.filter(course=course_id).order_by(
    #     'date_recorded').distinct('date_recorded')
    # attendance_present = attendance_list.filter(status=True)
    attendance_list = Attendance.objects.filter(course=course_id).order_by(
        'date_recorded')
    context = {
        'attendance_list': attendance_list,
    }
    return render(request, 'view_attendance_by_course.html', context)


# What the fuck is going on here
def student_attendance_per_course(request, course_id):
    attendance_list = Attendance.objects.filter(course=course_id).order_by(
        'date_recorded').distinct('date_recorded')
    lecturer = get_object_or_404(Lecturer, user=request.user)
    courses = get_object_or_404(Course, pk=course_id)
    students = StudentCourseRegistration.objects.filter(
        course=courses).filter(active=True)

    context = {
        'attendance_list': attendance_list,
        'students': students,
    }
    return render(request, 's', context)


def attendance_per_course_breakdown(request, course_id, attendance_date):
    print(attendance_date)
    attendance_list = Attendance.objects.filter(course_id=course_id,
                                                date_recorded__exact=attendance_date)
    students_present = list(attendance_list.values_list('student__user__username', flat=True))
    context = {
        'attendance_list': attendance_list,
        'students_present': students_present
        # 'attendance_present': len(attendance_present),
        # 'attendance_absent': len(attendance_list) - len(attendance_present)
    }
    return render(request, 'view_attendance_by_breakdown_course.html', context)


@method_decorator([login_required, teacher_required], name='dispatch')
class AttendanceUpdate(UpdateView):
    model = Attendance
    # fields = ['student']
    template_name = 'attendance_edit.html'
    form_class = AttendanceForm

course/templates/course_list.html
{% extends 'base_dashboard.html' %}
{% load static %}

{% block css %}
{{ block.super }}
<!-- x-editor CSS
		============================================ -->
<link rel="stylesheet" href="{% static 'css/editor/select2.css' %}">
<link rel="stylesheet" href="{% static 'css/editor/datetimepicker.css' %}">
<link rel="stylesheet" href="{% static 'css/editor/bootstrap-editable.css' %}">
<link rel="stylesheet" href="{% static 'css/editor/x-editor-style.css' %}">
<!-- normalize CSS ============================================ -->
<link rel="stylesheet" href="{% static 'css/data-table/bootstrap-table.css' %}">
<link rel="stylesheet" href="{% static 'css/data-table/bootstrap-editable.css' %}">

{% endblock %}

{% block content %}
<div class="data-table-area mg-b-15">
    <div class="container-fluid">
        <div class="row">
            <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                <div class="sparkline13-list">
                    <div class="sparkline13-hd">
                        <div class="main-sparkline13-hd">
                            <h1>All Course <span class="table-project-n">Data</span> Table</h1>
                        </div>
                    </div>
                    <div class="sparkline13-graph">
                        <div class="datatable-dashv1-list custom-datatable-overright">
                            <div id="toolbar">
                                <select class="form-control dt-tb">
                                    <option value="">Export Basic</option>
                                    <option value="all">Export All</option>
                                    <option value="selected">Export Selected</option>
                                </select>
                            </div>
                            <table id="table" data-toggle="table" data-pagination="true" data-search="true"
                                data-show-columns="true" data-show-pagination-switch="true" data-show-refresh="true"
                                data-key-events="true" data-show-toggle="true" data-resizable="true" data-cookie="true"
                                data-cookie-id-table="saveId" data-show-export="true" data-click-to-select="true"
                                data-toolbar="#toolbar">
                                <thead>
                                    <tr>
                                        <th data-field="state" data-checkbox="true"></th>
                                        <th data-field="id">Course ID</th>
                                        <th data-field="code">Course Code</th>
                                        <th data-field="name">Course Name</th>
                                        <th data-field="students_registered">No of Students Registered</th>
                                        <th data-field="take-attendance">Take Attendance</th>
                                        <th data-field="view-attendance">View Attendance</th>
                                        <th data-field="grading-attendance">View Attendance</th>


                                    </tr>
                                </thead>
                                <tbody>
                                    {% for course in courses %}
                                    <tr>
                                        <td></td>
                                        <td>{{ course.id }}</td>
                                        <td><a href="{% url 'course:courses_per_students' course.id %}">{{ course.course_code}}</a> </td>
                                        <td>{{ course.course_name }}</td>
                                        <td>{{ course.total_students}}</td>
                                        <td><a class="btn btn-info" href="{% url 'course:take_attendance' course.id %}">
                                                Take Attendance</a></td>
                                        <td><a class="btn btn-info" href="{% url 'course:view_attendance' course.id %}">
                                                View Attendance</a></td>
                                        <td>
                                            <button class="btn btn-info"><a
                                                    href="{% url 'course:view_attendance_marks' course.id %}">View
                                                    Grading</a>
                                            </button>
                                        </td>
                                    </tr>
                                    {% endfor %}

                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

{% block javascript %}
{{ block.super }}
<!-- data table JS
		============================================ -->
<script src="{% static 'js/data-table/bootstrap-table.js' %}"></script>
<script src="{% static 'js/data-table/tableExport.js' %}"></script>
<script src="{% static 'js/data-table/data-table-active.js' %}"></script>
<script src="{% static 'js/data-table/bootstrap-table-editable.js' %}"></script>
<script src="{% static 'js/data-table/bootstrap-editable.js' %}"></script>
<script src="{% static 'js/data-table/bootstrap-table-resizable.js' %}"></script>
<script src="{% static 'js/data-table/colResizable-1.5.source.js' %}"></script>
<script src="{% static 'js/data-table/bootstrap-table-export.js' %}"></script>
<!--  editable JS
		============================================ -->
<script src="{% static 'js/editable/jquery.mockjax.js' %}"></script>
<script src="{% static 'js/editable/mock-active.js' %}"></script>
<script src="{% static 'js/editable/select2.js' %}"></script>
<script src="{% static 'js/editable/moment.min.js' %}"></script>
<script src="{% static 'js/editable/bootstrap-datetimepicker.js' %}"></script>
<script src="{% static 'js/editable/bootstrap-editable.js' %}"></script>
<script src="{% static 'js/editable/xediable-active.js' %}"></script>
<!-- Chart JS
		============================================ -->
<script src="{% static 'js/chart/jquery.peity.min.js' %} "></script>
<script src="{% static 'js/peity/peity-active.js' %}"></script>
{% endblock %}

course/templates/view_attendance_by_breakdown_course.html
{% extends 'base_dashboard.html' %}
{% load static %}

{% block css %}
    {{ block.super }}
    <!-- x-editor CSS
		============================================ -->
    <link rel="stylesheet" href="{% static 'css/editor/select2.css' %}">
    <link rel="stylesheet" href="{% static 'css/editor/datetimepicker.css' %}">
    <link rel="stylesheet" href="{% static 'css/editor/bootstrap-editable.css' %}">
    <link rel="stylesheet" href="{% static 'css/editor/x-editor-style.css' %}">
    <!-- normalize CSS
		============================================ -->
    <link rel="stylesheet" href="{% static 'css/data-table/bootstrap-table.css' %}">
    <link rel="stylesheet" href="{% static 'css/data-table/bootstrap-editable.css' %}">

{% endblock %}

{% block content %}
    <div class="data-table-area mg-b-15">
        <div class="container-fluid">
            <div class="row">
                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                    <div class="sparkline13-list">
                        <div class="sparkline13-hd">
                            <div class="main-sparkline13-hd">
                                <h1>Attendance By <span class="table-project-n">Date</span> Table Breakdown</h1>
                            </div>
                        </div>
                        <div class="sparkline13-graph">
                            <div class="datatable-dashv1-list custom-datatable-overright">
                                <div id="toolbar">
                                    <select class="form-control dt-tb">
                                        <option value="">Export Basic</option>
                                        <option value="all">Export All</option>
                                        <option value="selected">Export Selected</option>
                                    </select>
                                </div>
                                <table id="table" data-toggle="table" data-pagination="true" data-search="true"
                                       data-show-columns="true" data-show-pagination-switch="true"
                                       data-show-refresh="true" data-key-events="true" data-show-toggle="true"
                                       data-resizable="true" data-cookie="true"
                                       data-cookie-id-table="saveId" data-show-export="true" data-click-to-select="true"
                                       data-toolbar="#toolbar">
                                    <thead>
                                    <tr>
                                        <th data-field="state" data-checkbox="true"></th>
                                        {#                                                <th data-field="id">ID</th>#}
                                        <th data-field="id">Date</th>
                                        <th data-field="code">Course Code</th>
                                        <th data-field="name">Course Name</th>
{#                                        <th data-field="students_name">Name</th>#}
                                        <th data-field="matric_no">Students present</th>
{#                                        <th data-field="attendance_status">Status</th>#}
                                        <th data-field="edit_btn">Edit</th>
                                    </tr>
                                    </thead>
                                    <tbody>
                                    {% for attendance in attendance_list %}
                                        <tr>
                                            <td></td>
                                            <td>{{ attendance.date_recorded }}</td>
                                            <td>{{ attendance.course.course_code }}</td>
                                            <td>{{ attendance.course.course_name }}</td>
                                            <td>{% for matric in students_present %} {{ matric }} <br /> {% endfor %}</td>

{#                                        {% for student in attendance.student_set.all %}#}
{#                                            <td>{{ student.full_name }}</td>#}
{#                                            <td>{{ student.matric_no }}</td>#}
{#{% endfor %}#}
{#                                            {% if attendance.attendance_status == 'Present' %}#}
{#                                                <td class="p-3 mb-2 bg-success text-white">{{ attendance.attendance_status }}</td>#}
{#                                            {% else %}#}
{#                                                <td class="p-3 mb-2 bg-danger text-white"> {{ attendance.attendance_status }}</td>#}
{#                                            {% endif %}#}

                                            <td>
                                                <a class="btn btn-info"
                                                   href="{% url 'course:attendance_update' attendance.id %}">Edit</a>

                                            </td>

                                        </tr>
                                    {% endfor %}

                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

{% block javascript %}
    {{ block.super }}
    <!-- data table JS
		============================================ -->
    <script src="{% static 'js/data-table/bootstrap-table.js' %}"></script>
    <script src="{% static 'js/data-table/tableExport.js' %}"></script>
    <script src="{% static 'js/data-table/data-table-active.js' %}"></script>
    <script src="{% static 'js/data-table/bootstrap-table-editable.js' %}"></script>
    <script src="{% static 'js/data-table/bootstrap-editable.js' %}"></script>
    <script src="{% static 'js/data-table/bootstrap-table-resizable.js' %}"></script>
    <script src="{% static 'js/data-table/colResizable-1.5.source.js' %}"></script>
    <script src="{% static 'js/data-table/bootstrap-table-export.js' %}"></script>
    <!--  editable JS
		============================================ -->
    <script src="{% static 'js/editable/jquery.mockjax.js' %}"></script>
    <script src="{% static 'js/editable/mock-active.js' %}"></script>
    <script src="{% static 'js/editable/select2.js' %}"></script>
    <script src="{% static 'js/editable/moment.min.js' %}"></script>
    <script src="{% static 'js/editable/bootstrap-datetimepicker.js' %}"></script>
    <script src="{% static 'js/editable/bootstrap-editable.js' %}"></script>
    <script src="{% static 'js/editable/xediable-active.js' %}"></script>
    <!-- Chart JS
		============================================ -->
    <script src="{% static 'js/chart/jquery.peity.min.js' %} "></script>
    <script src="{% static 'js/peity/peity-active.js' %}"></script>
{% endblock %}