accounts/urls.py
from django.urls import path
from .views import (StudentSignUpView, LecturerSignUpView, UpdateStudent,
                    user_login, student_image_login, image_registration,
                    StudentDetail, LecturerDetail, UpdateLecturer, UpdateUser)
from django.contrib.auth import views

app_name = 'accounts'

urlpatterns = [
    path('lecturer/register/', LecturerSignUpView.as_view(),
         name='lecturer_register'),
    path('add-student/', StudentSignUpView.as_view(), name='add_student'),
    path('user/login/', user_login, name='user_login_redirect'),
    path('student/image/login/<int:pk>/',
         student_image_login, name='student_image_login'),
    path('update-student/<int:pk>/',
         UpdateStudent.as_view(), name='update_student'),
    path('student/details/<int:pk>/',
         StudentDetail.as_view(), name='student_detail'),
    path('lecturer/details/<int:pk>/',
         LecturerDetail.as_view(), name='lecturer_detail'),
    path('update-lecturer/<int:pk>/',
         UpdateLecturer.as_view(), name='update_lecturer'),
    path('update-user/<int:pk>/',
         UpdateUser.as_view(), name='update_user'),
    path('image-registration/<int:pk>',
         image_registration, name='image_register'),
    path('reset', views.PasswordResetView.as_view(
        template_name='password_reset_form.html', email_template_name='password_reset_email.html',
        subject_template_name='password_reset_subject.txt'),
        name='password_reset'
    ),

    path('reset/done', views.PasswordResetDoneView.as_view(
        template_name='password_reset_done.html'
    ), name='password_reset_done'),

    path('reset/<uidb64>/<token>/', views.PasswordResetConfirmView.as_view(
        template_name='password_reset_confirm.html'),
        name='password_reset_confirm'),

    path('account/reset/complete/',
         views.PasswordResetCompleteView.as_view(
             template_name='password_reset_complete.html'),
         name='password_reset_complete'),

    path('settings/password/', views.PasswordChangeView.as_view(template_name='password_change.html'),
         name='password_change'),

    path('settings/password/done/', views.PasswordChangeDoneView.as_view(
        template_name='password_change_done.html'),
        name='password_change_done'
    ),

    path('login/', views.LoginView.as_view(template_name='login.html'), name='login'),

]

course/urls.py
from django.urls import path
from .views import (dashboard, CreateCourse, CourseList, StudentProfile, StudentsPerCourseList, student_course_registration, all_students_per_lecturer,
                    take_attendance, attendance_per_course,attendance_per_course_breakdown, AttendanceUpdate, 
                    calculate_percentage_of_attendance)

app_name = 'course'

urlpatterns = [
    path('dashboard/', dashboard, name='user_dashboard'),
    path('create-course/', CreateCourse.as_view(), name='create_course'),
    path('courses-list', CourseList.as_view(), name='course_list'),
    path('lecturer/student/<int:pk>', StudentProfile.as_view(), name='lecturer_student'),
    path('course/students/<int:pk>', StudentsPerCourseList.as_view(), name='courses_per_students'),

    path('student/<int:pk>/registration/',
         student_course_registration, name='student_registration'),
    path('all/student/',
         all_students_per_lecturer, name='all_student_per_lecturer'),

    path('attendance-update/<int:pk>/',
         AttendanceUpdate.as_view(), name='attendance_update'),
    path('take-attendance/<int:course_id>',
         take_attendance, name='take_attendance'),
    path('view-attendance/<int:course_id>',
         attendance_per_course, name='view_attendance'),
    path('view-attendance/marks/<int:course_id>',
         calculate_percentage_of_attendance, name='view_attendance_marks'),
    path('view-attendance-breakdown/<int:course_id>/<slug:attendance_date>', attendance_per_course_breakdown,
         name='view_attendance_breakdown')


]

facettendace/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('', include('course.urls'))
]


if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls))] + urlpatterns
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)

accounts/models.py
from django.contrib.auth.models import AbstractUser
from django.contrib.auth.models import User
from django.db import models
from django.utils.translation import ugettext_lazy as _
from phonenumber_field.modelfields import PhoneNumberField

from .validators import UnicodeUsernameValidator


class User(AbstractUser):
    MALE = 'MALE'
    FEMALE = 'FEMALE'
    OTHERS = 'OTHERS'
    GENDER_CHOICES = [
        (MALE, 'Male'),
        (FEMALE, 'Female'),
        (OTHERS, 'Others'),
    ]
    username = models.CharField(max_length=40, unique=True)
    email = models.EmailField(_('email address'), null=True,)

    USERNAME_FIELD = 'username'

    gender = models.CharField(choices=GENDER_CHOICES, max_length=6)
    dept = models.CharField(_("Your Department"), blank=True, max_length=255)
    phone_number = PhoneNumberField(blank=True, default='')
    address = models.CharField(max_length=500, default='')
    is_student = models.BooleanField(default=False)
    is_teacher = models.BooleanField(default=False)

    # REQUIRED_FIELDS = ['email', 'username']

    def __init__(self, *args, **kwargs):
        validate_username = UnicodeUsernameValidator()
        super(User, self).__init__(*args, **kwargs)
        self._meta.get_field('username').validators = [validate_username]


class Lecturer(models.Model):
    user = models.OneToOneField(
        User, on_delete=models.CASCADE, primary_key=True)

    qualification = models.CharField(max_length=200)
    image = models.ImageField(upload_to='lecturers', null=True, blank=True)

    class Meta:
        verbose_name = "Lecturer"
        verbose_name_plural = "Lecturers"

    def __str__(self):
        return self.user.username

    @property
    def full_name(self):
        return f"{self.user.first_name} {self.user.last_name}"

    @property
    def courses_registered(self):
        return self.course_set.all()


class Student(models.Model):
    LEVEL_ONE = '100'
    LEVEL_TWO = '200'
    LEVEL_THREE = '300'
    LEVEL_FOUR = '400'
    LEVEL_FIVE = '500'
    LEVEL_SIX = '600'

    LEVEL_CHOICE = [
        (LEVEL_ONE, '100L'),
        (LEVEL_TWO, '200L'),
        (LEVEL_THREE, '300L'),
        (LEVEL_FOUR, '400L'),
        (LEVEL_FIVE, '500L'),
        (LEVEL_SIX, '600L'),

    ]
    user = models.OneToOneField(
        User, on_delete=models.CASCADE, primary_key=True)
    image = models.ImageField(upload_to='students', null=True, blank=True)

    level = models.CharField(_('Your Level'), blank=True,
                             choices=LEVEL_CHOICE, max_length=4)

    def __str__(self):
        return self.user.username

    @property
    def full_name(self):
        return f"{self.user.first_name} {self.user.last_name}"

    @property
    def courses_registered(self):
        return self.studentcourseregistration_set.filter(active=True)

# @receiver(post_save, sender=User)
# def create_or_update_lecturer_profile(sender, instance, created, **kwargs):
#     if created:
#         Lecturer.objects.create(user=instance)
#     instance.lecturer.save()

accounts/views.py
from django.http import HttpResponse
from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse, reverse_lazy
from .forms import UserRegistrationForm, LecturerSignUpForm, StudentSignUpForm
from django.views.generic.edit import FormView, CreateView, UpdateView
from django.views.generic import DetailView
from .mixins import ViewPermissionMixin
from django.contrib.auth import authenticate, login, logout
from .models import Lecturer, Student
# from django.contrib.auth.models import User
from django.core.files.storage import default_storage
from .utils import convert64toImage, face_rec_login, encoded_face
from django.contrib import messages
from django.contrib.auth import get_user_model

User = get_user_model()
class StudentSignUpView(CreateView):
    model = User
    form_class = StudentSignUpForm
    template_name = 'register.html'

    def get_context_data(self, **kwargs):
        kwargs['user_type'] = 'student'
        return super().get_context_data(**kwargs)

    def form_valid(self, form):
        user = form.save()
        matric_no = user.username
        user.save()
        login(self.request, user)
        student = Student.objects.get(user__username=matric_no)
        print(student.pk)
        return redirect(reverse('accounts:image_register', args=[student.pk]))


class LecturerSignUpView(CreateView):
    model = User
    form_class = LecturerSignUpForm
    template_name = 'register.html'

    def get_context_data(self, **kwargs):
        kwargs['user_type'] = 'Lecturer'
        return super().get_context_data(**kwargs)

    def form_valid(self, form):
        user = form.save()
        # matric_no = user.cleaned_data['user']
        # user.save()
        login(self.request, user)
        # student = Student.objects.get(matric_no=matric_no)
        return redirect(reverse('course:user_dashboard'))


# def user_registration(request):
#     if request.method == 'POST':
#         user_form = UserRegistrationForm(request.POST)
#         if user_form.is_valid():
#             user_form.save(commit=False)
#             username = user_form.cleaned_data['username']
#             password = user_form.cleaned_data['password1']
#             email = user_form.cleaned_data['email']

#             user = user_form.save()
#             Lecturer.objects.update_or_create(
#                 user=user,
#                 defaults={
#                     "gender": user_form.cleaned_data['gender'],
#                     "qualification": user_form.cleaned_data['qualification'],

#                 }
#             )
#             user = authenticate(request, username=username, password=password)
#             login(request, user)

#             return redirect('course:user_dashboard')
#     else:
#         user_form = UserRegistrationForm()

#     context = {
#         'form': user_form
#     }

#     return render(request, 'register.html', context)


def user_login(request):
    if request.user.is_student:
        student = Student.objects.get(user=request.user)
        print(student.pk)
        if student.image:
            return redirect(reverse('accounts:student_image_login', args=[student.pk]))
        else:
            return redirect(reverse('accounts:image_register', args=[student.pk]))
    else:
        return redirect(reverse('course:user_dashboard'))


def student_image_login(request, pk):
    student = get_object_or_404(Student, pk=pk)
    images_array, first_names, matric_nos = [student.image.path], [
        student.user.first_name], [student.user.username]
    authenticated = face_rec_login(
        images_array, first_names, matric_nos, student_login=True)

    if authenticated:
        request.session['student'] = student.pk
        return redirect(reverse('accounts:student_detail', args=[pk]))

    else:
        messages.error(request, 'Login failed')
        return redirect('accounts:student_login')


# class CreateStudent(CreateView):
#     model = Student
#     fields = ['first_name', 'last_name',
#               'matric_no', 'dept', 'school', 'level']
#     template_name = 'add_student.html'

#     def get_success_url(self):
#         if not self.success_url:
#             return reverse_lazy('accounts:image_register', args=[self.object.id])


class StudentDetail(ViewPermissionMixin, DetailView):
    model = Student
    template_name = 'profile.html'
    context_object_name = 'profile_detail'

    def dispatch(self, request, *args, **kwargs):
        try:
            if int(kwargs['pk']) != request.session['student'] or not request.user.is_authenticated:
                messages.warning(
                    request, 'You do not have access to view this page')
                return redirect('accounts:student_login')
        except KeyError:
            return redirect('accounts:student_login')

        return super(StudentDetail, self).dispatch(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["student_profile"] = True
        # context['courses_registered'] = self.studentcourseregistration_set.filter(active=True)
        return context


class LecturerDetail(ViewPermissionMixin, DetailView):
    model = Lecturer
    template_name = 'lecturer-profile.html'
    context_object_name = 'profile_detail'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["lecturer_profile"] = True
        # context['courses_registered'] = self.studentcourseregistration_set.filter(active=True)
        return context


class UpdateLecturer(UpdateView):
    model = Lecturer
    fields = ['gender', 'qualification', 'image',
              'dept', 'school', 'phone_number', 'address']
    template_name = 'update_lecturer.html'

    context_object_name = 'lecturer'

    def get_context_data(self, **kwargs):

        context = super(UpdateLecturer, self).get_context_data(**kwargs)
        context['update'] = True

        return context

    def get_success_url(self):
        if not self.success_url:
            return reverse_lazy('accounts:lecturer_detail', args=[self.object.id])


class UpdateUser(UpdateView):
    model = User
    fields = ['email']
    template_name = 'update_lecturer.html'

    context_object_name = 'lecturer'

    def get_context_data(self, **kwargs):

        context = super(UpdateUser, self).get_context_data(**kwargs)
        context['update'] = True

        return context

    def get_success_url(self):
        if not self.success_url:
            return reverse_lazy('accounts:lecturer_detail', args=[self.object.id])


class UpdateStudent(UpdateView):
    model = User
    fields = ['first_name', 'last_name', 'email', 'username', 'gender', 'dept', 'phone_number']
    template_name = 'add_student.html'
    context_object_name = 'student'

    # def get_object(self, queryset=None):
    #     if queryset is None:
    #         queryset = self.get_queryset()
    #         print(queryset)
    #     return get_object_or_404(Student, pk=self.kwargs['pk'])

    def get_context_data(self, **kwargs):
        context = super(UpdateStudent, self).get_context_data(**kwargs)
        # context['user'] = User.objects.get(student__pk=self.kwargs['pk'])  # whatever you would like
        context['update'] = True
        return context

    def get_success_url(self):
        if not self.success_url:
            return reverse_lazy('accounts:image_register', args=[self.object.id])


def image_registration(request, pk):
    if request.method == 'POST':
        image = request.POST['autentication_image']
        user = get_object_or_404(Student, pk=pk)
        user_image = convert64toImage(image, user.user.first_name)
        temppath = default_storage.save('temp.png', content=user_image)
        temp_filepath = default_storage.path(temppath)
        face_accepted = encoded_face(temp_filepath)
        if face_accepted:
            user.image = user_image
            user.save()
            default_storage.delete(temppath)
            return redirect('course:user_dashboard')
        else:
            default_storage.delete(temppath)
            messages.warning(request, 'Face Not decteted.')

        default_storage.delete(temppath)
    return render(request, 'auth_image.html')

accounts/templates/lecturer-profile.html
{% extends 'base_dashboard.html' %}
{% load static %}

{% block css %}
{{ block.super }}
<!-- x-editor CSS
		============================================ -->
<link rel="stylesheet" href="{% static 'css/editor/select2.css' %}">
<link rel="stylesheet" href="{% static 'css/editor/datetimepicker.css' %}">
<link rel="stylesheet" href="{% static 'css/editor/bootstrap-editable.css' %}">
<link rel="stylesheet" href="{% static 'css/editor/x-editor-style.css' %}">
<!-- normalize CSS
		============================================ -->
<link rel="stylesheet" href="{% static 'css/data-table/bootstrap-table.css' %}">
<link rel="stylesheet" href="{% static 'css/data-table/bootstrap-editable.css' %}">

{% endblock %}

{% block head_title %} {{ profile_detail.full_name}} Profile {% endblock %}

{% block content %}
<!-- Single pro tab review Start-->
<div class="single-pro-review-area mt-t-30 mg-b-15">
    <div class="container-fluid">
        <div class="row">
            <div class="col-lg-4 col-md-4 col-sm-4 col-xs-12">
                <div class="profile-info-inner">
                    <div class="profile-img">
                        <img src="{{profile_detail.image.url}}" alt="" />
                        <a class="btn btn-info center-block"
                            href="{% url 'accounts:image_register' profile_detail.id %}">Change picture</a>
                    </div>
                    <div class="profile-details-hr">
                        <div class="row">
                            <div class="col-lg-12">
                                <div class="address-hr">
                                    <p><b>Name</b><br /> {{profile_detail.full_name}} </p>
                                </div>
                            </div>
                        </div>

                        <div class="row">
                            <div class="col-lg-6 col-md-12 col-sm-12 col-xs-6">
                                <div class="address-hr tb-sm-res-d-n dps-tb-ntn">
                                    <p><b>Gemder</b><br /> {{profile_detail.gender}}</p>
                                </div>
                            </div>
                            <div class="col-lg-6 col-md-12 col-sm-12 col-xs-6">
                                <div class="address-hr tb-sm-res-d-n dps-tb-ntn">
                                    <p><b>Department</b><br /> {{profile_detail.dept}}</p>
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-lg-6 col-md-12 col-sm-12 col-xs-6">
                                <div class="address-hr">
                                    <p style="word-wrap: break-word;"><b>Email ID</b><br />
                                        {{profile_detail.user.email}}</p>
                                </div>
                            </div>
                            <div class="col-lg-6 col-md-12 col-sm-12 col-xs-6">
                                <div class="address-hr tb-sm-res-d-n dps-tb-ntn">
                                    <p><b>Phone</b><br /> {{profile_detail.phone_number}}</p>
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-lg-12">
                                <div class="address-hr">
                                    <p><b>Address</b><br /> {{profile_detail.address}}</p>
                                </div>
                            </div>
                        </div>

                    </div>
                </div>
            </div>
            <div class="col-lg-8 col-md-8 col-sm-8 col-xs-12">
                <div class="product-payment-inner-st res-mg-t-30 analysis-progrebar-ctn">
                    <ul id="myTabedu1" class="tab-review-design">
                        <li class="active"><a href="#description">Details</a></li>
                        <!-- <li><a href="#reviews"> Biography</a></li> -->
                        <li><a href="{% url 'accounts:update_lecturer' profile_detail.id %}">Update Details</a></li>
                        <li><a href="{% url 'accounts:update_user' profile_detail.id %}">Update Email</a></li>

                    </ul>
                    <div id="myTabContent" class="tab-content custom-product-edit st-prf-pro">
                        <div class="product-tab-list tab-pane fade active in" id="description">
                            <div class="row">
                                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                                    <div class="review-content-section">
                                        <div class="row">
                                            <div class="col-lg-3 col-md-3 col-sm-3 col-xs-6">
                                                <div class="address-hr biography">
                                                    <p><b>Full Name</b><br /> {{profile_detail.full_name}}</p>
                                                </div>
                                            </div>
                                            <div class="col-lg-3 col-md-3 col-sm-3 col-xs-6">
                                                <div class="address-hr biography">
                                                    <p><b>Gender</b><br /> {{profile_detail.gender}}</p>
                                                </div>
                                            </div>
                                            <div class="col-lg-3 col-md-3 col-sm-3 col-xs-6">
                                                <div class="address-hr biography">
                                                    <p style="word-wrap: break-word;"><b>Email</b><br />
                                                        {{profile_detail.user.email}}</p>
                                                </div>
                                            </div>
                                            <div class="col-lg-3 col-md-3 col-sm-3 col-xs-6">
                                                <div class="address-hr biography">
                                                    <p><b>Mobile</b><br /> {{profile_detail.phone_number}}</p>
                                                </div>
                                            </div>
                                        </div>
                                        <div class="row">
                                            <div class="col-lg-12">
                                                <div class="row">
                                                    <div class="col-lg-12">
                                                        <div class="skill-title">
                                                            <h2>Courses Created</h2>
                                                            <hr />
                                                        </div>
                                                    </div>
                                                </div>
                                                <div class="ex-pro">
                                                    <ul>
                                                        {% for course in profile_detail.courses_registered %}
                                                        <li><i class="fa fa-angle-right"></i>{{course.full_course_name}}
                                                        </li>
                                                        {% empty %}
                                                        <h3>No course Registrered</h3>
                                                        {% endfor %}
                                                    </ul>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<div class="footer-copyright-area">
    <div class="container-fluid">
        <div class="row">
            <div class="col-lg-12">
                <div class="footer-copy-right">
                    <p>Copyright © 2018. All rights reserved. Template by <a
                            href="https://colorlib.com/wp/templates/">Colorlib</a></p>
                </div>
            </div>
        </div>
    </div>
</div>
</div>
{% endblock %}

accounts/templates/login.html
{%extends 'base.html'%} 
{% block head_title %} Log in to Faceattendace{%endblock%}
 {% block contents%}

<div class="row center-element">
  <div class="col-lg-4 col-md-6 col-sm-8">
    <div class="card">
      <div class="card-body">
        <h3 class="card-title text-center">Log in</h3>
        <form method="post" novalidate>
          {% csrf_token %}
          <input type="hidden" name="next" value="{{ next }}" />
          {% include 'includes/forms.html' %}
          <button type="submit" class="btn btn-primary btn-block">
            Log in
          </button>
        </form>
      </div>
      <div class="card-footer text-muted text-center">
        New to Faceattendace?
        {% comment %} <a href="{% url 'accounts:Register' %}">Sign up</a> {% endcomment %}
      </div>
    </div>
    <div class="text-center py-2">
      <strong>
        <a href="{%url 'accounts:password_reset'%}" class="text-muted"
          >Forgot your password?</a
        >
      </strong>
    </div>
  </div>
</div>
{% endblock %}

accounts/templates/logout.html
{% extends "base.html" %}

{% load i18n %}

{% block head_title %}{% trans "Sign Out" %}{% endblock %}

{% block inner %}
<h1>{% trans "Sign Out" %}</h1>

<p>{% trans 'Are you sure you want to sign out?' %}</p>

<form method="post" action="{% url 'account_logout' %}">
  {% csrf_token %}
  {% if redirect_field_value %}
  <input type="hidden" name="{{ redirect_field_name }}" value="{{ redirect_field_value }}"/>
  {% endif %}
  <button class="btn btn-danger" type="submit">{% trans 'Sign Out' %}</button>
</form>


{% endblock %}

accounts/templates/password_change.html
{% extends 'base.html' %}

{% block head_title %}Change password{% endblock %}

{% block breadcrumb %}
<li class="breadcrumb-item active">Change password</li>
{% endblock %}

{% block contents %}
<div class="row justify-content-center center-element">
  <div class="col-lg-6 col-md-8 col-sm-10">
    <form method="post" novalidate>
      {% csrf_token %}
      {% include 'includes/forms.html' %}
      <button type="submit" class="btn btn-success">Change password</button>
    </form>
  </div>
</div>
{% endblock %}

accounts/templates/password_change_done.html
{% extends 'base.html' %}

{% block head_title %}Change password successful{% endblock %}

{% block breadcrumb %}
  <li class="breadcrumb-item"><a href="{% url 'password_change' %}">Change password</a></li>
  <li class="breadcrumb-item active">Success</li>
{% endblock %}

{% block content %}
  <div class="alert alert-success" role="alert">
    <strong>Success!</strong> Your password has been changed!
  </div>
  <a href="{% url 'course:dashboard' %}" class="btn btn-secondary">Return to home page</a>
{% endblock %}

accounts/templates/password_reset.html
{% extends "account/base.html" %}

{% load i18n %}
{% load account %}
{% load crispy_forms_tags %}

{% block head_title %}{% trans "Password Reset" %}{% endblock %}

{% block inner %}

    <h1>{% trans "Password Reset" %}</h1>
    {% if user.is_authenticated %}
    {% include "account/snippets/already_logged_in.html" %}
    {% endif %}

    <p>{% trans "Forgotten your password? Enter your e-mail address below, and we'll send you an e-mail allowing you to reset it." %}</p>

    <form method="POST" action="{% url 'account_reset_password' %}" class="password_reset">
        {% csrf_token %}
        {{ form|crispy }}
        <input class="btn btn-primary" type="submit" value="{% trans 'Reset My Password' %}" />
    </form>

    <p>{% blocktrans %}Please contact us if you have any trouble resetting your password.{% endblocktrans %}</p>
{% endblock %}

accounts/templates/password_reset_complete.html
{% extends 'base.html' %}

{% block title %}Password changed!{% endblock %}

{% block contents %}
<div class="row justify-content-center center-element">
  <div class="col-lg-6 col-md-8 col-sm-10">
    <div class="card">
      <div class="card-body">
        <h3 class="card-title">Password changed!</h3>
        <div class="alert alert-success" role="alert">
          You have successfully changed your password! You may now proceed to log in.
        </div>
        <a href="{% url 'accounts:login' %}" class="btn btn-secondary btn-block">Return to log in</a>
      </div>
    </div>
  </div>
</div>
{% endblock %}

accounts/templates/password_reset_confirm.html
{% extends 'base.html' %}

{% block head_title %}
{% if validlink %}
Change password for {{ form.user.username }}
{% else %}
Reset your password
{% endif %}
{% endblock %}

{% block content %}
<div class="row justify-content-center center-element">
  <div class="col-lg-6 col-md-8 col-sm-10">
    <div class="card">
      <div class="card-body">
        {% if validlink %}
        <h3 class="card-title">Change password for @{{ form.user.username }}</h3>
        <form method="post" novalidate>
          {% csrf_token %}
          {% include 'includes/forms.html' %}
          <button type="submit" class="btn btn-success btn-block">Change password</button>
        </form>
        {% else %}
        <h3 class="card-title">Reset your password</h3>
        <div class="alert alert-danger" role="alert">
          It looks like you clicked on an invalid password reset link. Please try again.
        </div>
        <a href="{% url 'accounts:password_reset' %}" class="btn btn-secondary btn-block">Request a new password reset
          link</a>
        {% endif %}
      </div>
    </div>
  </div>
</div>
{% endblock %}

accounts/templates/password_reset_email.html
Hi there,

Someone asked for a password reset for the email address {{ email }}.
Follow the link below:
{{ protocol }}://{{ domain }}{% url 'accounts:password_reset_confirm' uidb64=uid token=token %}

In case you forgot your Faceattendace username: {{ user.username }}

If clicking the link above doesn't work, please copy and paste the URL
in a new browser window instead.

If you've received this mail in error, it's likely that another user entered
your email address by mistake while trying to reset a password. If you didn't
initiate the request, you don't need to take any further action and can safely
disregard this email.

Thanks,

The Facettendance Team

accounts/templates/password_reset_form.html
{% extends 'base.html' %}

{% block head_title %}Reset your password{% endblock %}

{% block contents %}
<div class="row justify-content-center center-element">
  <div class="col-lg-4 col-md-6 col-sm-8">
    <div class="card">
      <div class="card-body">
        <h3 class="card-title">Reset your password</h3>
        <p>Enter your email address and we will send you a link to reset your password.</p>
        <form method="post" novalidate>
          {% csrf_token %}
          {% include 'includes/forms.html' %}
          <button type="submit" class="btn btn-primary btn-block">Send password reset email</button>
        </form>
      </div>
    </div>
  </div>
</div>
{% endblock %}